sudo: required
services:
  - docker

before_install:
  - docker build -t lftconcept/docker-simple-frontend -f Dockerfile.dev .

script:
  - docker run lftconcept/docker-simple-frontend npm run test -- --coverage
